### ISSUE TITLE
New Issue, something went wrong

### ISSUE THREAD

**Issue by SoloHam** [thelevicole/youtube-to-html5-loader#17]
https://yt2html5.com/

![image](https://user-images.githubusercontent.com/8042978/134395069-8361a79b-f5cc-4561-9731-64b023af9f09.png)

**Comment by sghosh1810** [comment]
Same

**Comment by thelevicole** [comment]
Yes sorry, the shared server this api is served from is having outages. I'm looking at moving providers.

**Comment by SoloHam** [comment]
Can you also please provide a Github repo for the server, so if people wanted to host them by themselves they could. That way you won't get much burdened either.

**Comment by thelevicole** [comment]
@SoloHam great idea! It's such a simple setup. I shall share when I'm back at my computer.

**Comment by sghosh1810** [comment]
![Screenshot 2021-09-29 at 11 04 26 PM](https://user-images.githubusercontent.com/12782032/135320046-177b4edb-4af6-4bbe-8d14-29a0efe7c750.png)

**Comment by yakyouk** [comment]
> @SoloHam great idea! It's such a simple setup. I shall share when I'm back at my computer.

Thank you for this great library! Would it be ok to share the server setup?

**Comment by thelevicole** [comment]
Closing this as the new release includes support for self hosting the man-in-the-middle API. Thanks for your patience!
