### ISSUE TITLE
1080p video quality is not available

### ISSUE THREAD

**Issue by gzalinski** [thelevicole/youtube-to-html5-loader#2]
I found that in the parameters exist 1080p, but it is not returned.

**Comment by thelevicole** [comment]
Some videos on YouTube do not have `1080p` streams, however, they might have `1080pna`. 

You can add a list of supported formats in order of priority like so:

```javascript
new YouTubeToHtml5({
  formats: [ '1080pna', '1080p' ]
});
```

Please note that a new release has been published. 

Hope this helps.
