### ISSUE TITLE
How to use it with es6 modules

### ISSUE THREAD

**Issue by grcmichael** [thelevicole/youtube-to-html5-loader#7]
Hi, I'd like to use your library using es6 modules,
so I can use the `import` syntaxe.
Indeed the `require()` syntaxe doesn't work with my workflow.

Can I do this with your module ?
Thank you very much

**Comment by nopol10** [comment]
Use
```
import YouTubeToHtml5 from "@thelevicole/youtube-to-html5-loader";
```

**Comment by grcmichael** [comment]
thanks a lot for your answer, i added useless brace char !
